import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Model from "../app/component/Model"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trello_2.O',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Model/>
        </body>
    </html>
  )
}
